package cmd

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/kota65535/ghs/internal/diff"
	"github.com/kota65535/ghs/internal/resource"
	"github.com/kota65535/ghs/internal/schema"
)

// repositoryKey stands for the repository's own fields in the resource
// selection. Everything else is selected by the key it is written under, but
// the repository is the top level of the file and has no key of its own.
const repositoryKey = "repository"

func newInitCommand(global *globalOptions) *cobra.Command {
	var force bool

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Write a settings file from the repository's current settings",
		Long: "init asks which resources to manage and writes the settings the\n" +
			"repository has right now, so that the first plan reports no changes and\n" +
			"the file can be trimmed down from there.\n\n" +
			"Only writable fields are written: what the API reports and no request\n" +
			"accepts -- an id, a timestamp -- is left out. A resource that is not\n" +
			"selected is not written at all, which is what leaves it unmanaged.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if _, err := os.Stat(global.file); err == nil && !force {
				return fmt.Errorf("%s already exists (pass --force to overwrite it)", global.file)
			}

			repo, err := resolveRepo(global.repo)
			if err != nil {
				return err
			}

			selected, err := selectResources()
			if err != nil {
				return err
			}
			if len(selected) == 0 {
				return nil
			}

			client, err := newClient()
			if err != nil {
				return err
			}

			settings, err := generate(cmd.Context(), client, repo, selected)
			if err != nil {
				return err
			}

			if err := writeFile(global.file, settings); err != nil {
				return err
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Wrote %s from %s. Run `ghs plan` to check it.\n", global.file, repo)
			return nil
		},
	}

	cmd.Flags().BoolVar(&force, "force", false, "overwrite the settings file if it exists")

	return cmd
}

// resourceKeys are the resources init offers, in the order they are offered:
// the repository itself first, then each key that may be written under it.
func resourceKeys() []string {
	return append([]string{repositoryKey}, schema.Root().ChildNames()...)
}

// selectResources asks which resources to manage.
//
// Every resource starts selected, since a file describing all of them is the
// answer more often than not, and deselecting the ones you do not want is less
// work than checking off the ones you do.
func selectResources() ([]string, error) {
	selected := resourceKeys()

	form := huh.NewForm(huh.NewGroup(
		huh.NewMultiSelect[string]().
			Title("Resources to manage").
			Description("Anything left unselected is not written to the file, and so is not managed.").
			Options(huh.NewOptions(resourceKeys()...)...).
			Value(&selected),
	))
	if err := form.Run(); err != nil {
		return nil, fmt.Errorf("select resources: %w", err)
	}

	sort.Strings(selected)
	return selected, nil
}

// generate reads the current settings of the selected resources and renders
// them as a settings file.
//
// Each resource is rendered separately and the results concatenated, which is
// what keeps the repository's own fields at the top: a single mapping would
// come out with the keys sorted, leaving the actions block in the middle of
// them.
func generate(ctx context.Context, client resource.Client, repo resource.Repo, selected []string) ([]byte, error) {
	root := schema.Root()
	path := resource.At(repo)

	ordered, err := order(selected)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "# Generated by `ghs init` from %s.\n", repo)
	buf.WriteString("# Fields left out of this file are not managed: ghs never touches them.\n")

	for _, key := range ordered {
		if key == repositoryKey {
			current, err := resource.ObjectFor("").Fetch(ctx, client, root, path)
			if err != nil {
				return nil, err
			}
			if err := encode(&buf, writableFields("", root.Fields, current)); err != nil {
				return nil, err
			}
			continue
		}

		node, _ := root.Child(key)
		value, err := fetchNode(ctx, client, key, node, path.Child(node.Segment))
		if err != nil {
			return nil, err
		}
		if value == nil {
			continue
		}
		if err := encode(&buf, map[string]any{key: value}); err != nil {
			return nil, err
		}
	}

	return buf.Bytes(), nil
}

// order puts the selected resources in the order they are written, which is
// the repository's own fields first: they are the top level of the file, so
// anything written under a key has to come after them.
func order(selected []string) ([]string, error) {
	wanted := make(map[string]bool, len(selected))
	for _, key := range selected {
		wanted[key] = true
	}

	ordered := make([]string, 0, len(selected))
	for _, key := range resourceKeys() {
		if wanted[key] {
			ordered = append(ordered, key)
			delete(wanted, key)
		}
	}

	if unknown := sortedKeys(wanted); len(unknown) > 0 {
		return nil, fmt.Errorf("unknown resource %q", unknown[0])
	}
	return ordered, nil
}

// encode appends one resource to the file, preceded by a blank line so that
// the sections stay apart. An empty mapping is skipped: a node whose settings
// this repository does not have is better left out than written as a bare key.
func encode(buf *bytes.Buffer, value map[string]any) error {
	if len(value) == 0 {
		return nil
	}

	buf.WriteString("\n")

	enc := yaml.NewEncoder(buf)
	enc.SetIndent(2)
	if err := enc.Encode(value); err != nil {
		return fmt.Errorf("render settings: %w", err)
	}
	return enc.Close()
}

// fetchNode returns the writable settings at one node of the schema and at
// every node below it, walking the same tree plan walks.
//
// It returns nil where there is nothing to write: a namespace whose children
// are all empty, or a node whose path this repository does not have.
func fetchNode(ctx context.Context, client resource.Client, key string, node schema.Node, path resource.Path) (any, error) {
	if node.IsCollection() {
		return fetchElements(ctx, client, key, node, path)
	}

	out := map[string]any{}

	if node.Writable() {
		current, err := resource.ObjectFor(key).Fetch(ctx, client, node, path)
		if err != nil {
			return nil, err
		}
		for name, value := range writableFields(key, node.Fields, current) {
			out[name] = value
		}
	}

	for _, name := range node.ChildNames() {
		child, _ := node.Child(name)
		value, err := fetchNode(ctx, client, join(key, name), child, path.Child(child.Segment))
		if err != nil {
			return nil, err
		}
		if value != nil {
			out[name] = value
		}
	}

	if len(out) == 0 {
		return nil, nil
	}
	return out, nil
}

// fetchElements returns the elements of a collection, each with whatever is
// written under it.
//
// A collection with no elements comes out as an empty sequence rather than as
// nothing at all: the key is being written because the set was selected, and
// declaring the empty set is how a repository with no rulesets is stated.
func fetchElements(ctx context.Context, client resource.Client, key string, node schema.Node, path resource.Path) (any, error) {
	collection := resource.CollectionFor(key)

	current, err := collection.FetchAll(ctx, client, node, path)
	if err != nil {
		return nil, err
	}

	out := make([]any, 0, len(current))
	for _, name := range sortedKeys(current) {
		element := writableFields(key, node.Fields, current[name])

		if len(node.Nodes) > 0 {
			elementPath, err := collection.ElementPath(path, current[name])
			if err != nil {
				return nil, err
			}
			for _, childName := range node.ChildNames() {
				child, _ := node.Child(childName)
				value, err := fetchNode(ctx, client, join(diff.ElementPath(key, name), childName), child,
					elementPath.Child(child.Segment))
				if err != nil {
					return nil, err
				}
				if value != nil {
					element[childName] = value
				}
			}
		}

		out = append(out, element)
	}

	return out, nil
}

// writableFields keeps what the API reported and a request would accept,
// dropping everything else: the fields only ever read back, and the fields
// this repository has nothing for.
//
// Nested objects are filtered to the depth the description defines. An object
// whose properties it leaves unspecified is carried over whole, since there is
// nothing to filter it against.
func writableFields(key string, fields map[string]schema.Field, current map[string]any) map[string]any {
	out := map[string]any{}

	for name, field := range fields {
		value, reported := current[name]
		if !reported || value == nil || unmanaged(key, name) {
			continue
		}

		if nested, ok := value.(map[string]any); ok && len(field.Fields) > 0 {
			filtered := writableFields(join(key, name), field.Fields, nested)
			if len(filtered) == 0 {
				continue
			}
			value = filtered
		}

		out[name] = value
	}

	return out
}

// unmanaged reports a writable field that init leaves out of the file.
//
// Both entries are fields a generated file would be worse for holding. name
// renames the repository, which is not a setting anyone means to manage in the
// same file as the merge options. security_and_analysis is reported for every
// repository but accepted only where the features behind it are available, so
// writing back what was read would fail the first apply on most repositories.
//
// Either can still be declared by hand; this is only about what init writes.
func unmanaged(key, name string) bool {
	if key != "" {
		return false
	}
	return name == schema.NameField || name == "security_and_analysis"
}

// writeFile puts the settings file in place, creating the directory it sits in.
func writeFile(path string, settings []byte) error {
	if dir := filepath.Dir(path); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, settings, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
