// Code generated by `go run ./gen`. DO NOT EDIT.
//
// Source: github/rest-api-description@fee3373e1517aa7a3510c5db165154f47baf8d97

package schema

//go:generate go run github.com/kota65535/ghs/gen

// generated holds the field definitions exactly as the description states
// them. See extra.go for the fields it is missing.
var generated = map[string]Resource{
	"repository": {
		Name: "repository",
		Kind: KindObject,
		// from PATCH /repos/{owner}/{repo}
		Fields: map[string]Field{
			"allow_auto_merge":             {Type: "boolean"},
			"allow_forking":                {Type: "boolean"},
			"allow_merge_commit":           {Type: "boolean"},
			"allow_rebase_merge":           {Type: "boolean"},
			"allow_squash_merge":           {Type: "boolean"},
			"allow_update_branch":          {Type: "boolean"},
			"archived":                     {Type: "boolean"},
			"default_branch":               {Type: "string"},
			"delete_branch_on_merge":       {Type: "boolean"},
			"description":                  {Type: "string"},
			"has_issues":                   {Type: "boolean"},
			"has_projects":                 {Type: "boolean"},
			"has_pull_requests":            {Type: "boolean"},
			"has_wiki":                     {Type: "boolean"},
			"homepage":                     {Type: "string"},
			"is_template":                  {Type: "boolean"},
			"merge_commit_message":         {Type: "string", Enum: []string{"BLANK", "PR_BODY", "PR_TITLE"}},
			"merge_commit_title":           {Type: "string", Enum: []string{"MERGE_MESSAGE", "PR_TITLE"}},
			"name":                         {Type: "string"},
			"private":                      {Type: "boolean"},
			"pull_request_creation_policy": {Type: "string", Enum: []string{"all", "collaborators_only"}},
			"security_and_analysis": {Type: "object", Fields: map[string]Field{
				"advanced_security": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
				"code_security": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
				"secret_scanning": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
				"secret_scanning_ai_detection": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
				"secret_scanning_delegated_alert_dismissal": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
				"secret_scanning_delegated_bypass": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
				"secret_scanning_delegated_bypass_options": {Type: "object", Fields: map[string]Field{
					"reviewers": {Type: "array"},
				}},
				"secret_scanning_non_provider_patterns": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
				"secret_scanning_push_protection": {Type: "object", Fields: map[string]Field{
					"status": {Type: "string"},
				}},
			}},
			"squash_merge_commit_message":    {Type: "string", Enum: []string{"BLANK", "COMMIT_MESSAGES", "PR_BODY"}},
			"squash_merge_commit_title":      {Type: "string", Enum: []string{"COMMIT_OR_PR_TITLE", "PR_TITLE"}},
			"use_squash_pr_title_as_default": {Type: "boolean"},
			"visibility":                     {Type: "string", Enum: []string{"private", "public"}},
			"web_commit_signoff_required":    {Type: "boolean"},
		},
	},
	"variables": {
		Name: "variables",
		Kind: KindCollection,
		// from POST /repos/{owner}/{repo}/actions/variables
		Fields: map[string]Field{
			"name":  {Type: "string"},
			"value": {Type: "string"},
		},
	},
	"rulesets": {
		Name: "rulesets",
		Kind: KindCollection,
		// from POST /repos/{owner}/{repo}/rulesets
		Fields: map[string]Field{
			"bypass_actors": {Type: "array"},
			"conditions": {Type: "object", Fields: map[string]Field{
				"ref_name": {Type: "object", Fields: map[string]Field{
					"exclude": {Type: "array"},
					"include": {Type: "array"},
				}},
			}},
			"enforcement": {Type: "string", Enum: []string{"active", "disabled", "evaluate"}},
			"name":        {Type: "string"},
			"rules":       {Type: "array"},
			"target":      {Type: "string", Enum: []string{"branch", "push", "tag"}},
		},
	},
	"environments": {
		Name: "environments",
		Kind: KindCollection,
		// from PUT /repos/{owner}/{repo}/environments/{environment_name}
		Fields: map[string]Field{
			"deployment_branch_policy": {Type: "object", Fields: map[string]Field{
				"custom_branch_policies": {Type: "boolean"},
				"protected_branches":     {Type: "boolean"},
			}},
			"prevent_self_review": {Type: "boolean"},
			"reviewers":           {Type: "array"},
			"wait_timer":          {Type: "integer"},
		},
	},
}
