// Code generated by `go run ./gen`. DO NOT EDIT.
//
// Source: github/rest-api-description@fee3373e1517aa7a3510c5db165154f47baf8d97

package schema

//go:generate go run github.com/kota65535/ghs/gen

// generated describes the settings file exactly as the API description
// states it. See extra.go for what it is missing.
var generated = Node{
	Kind:   KindObject,
	Method: "PATCH",
	// from PATCH /repos/{owner}/{repo}
	Fields: map[string]Field{
		"allow_auto_merge":             {Type: "boolean"},
		"allow_forking":                {Type: "boolean"},
		"allow_merge_commit":           {Type: "boolean"},
		"allow_rebase_merge":           {Type: "boolean"},
		"allow_squash_merge":           {Type: "boolean"},
		"allow_update_branch":          {Type: "boolean"},
		"archived":                     {Type: "boolean"},
		"default_branch":               {Type: "string"},
		"delete_branch_on_merge":       {Type: "boolean"},
		"description":                  {Type: "string"},
		"has_issues":                   {Type: "boolean"},
		"has_projects":                 {Type: "boolean"},
		"has_pull_requests":            {Type: "boolean"},
		"has_wiki":                     {Type: "boolean"},
		"homepage":                     {Type: "string"},
		"is_template":                  {Type: "boolean"},
		"merge_commit_message":         {Type: "string", Enum: []string{"BLANK", "PR_BODY", "PR_TITLE"}},
		"merge_commit_title":           {Type: "string", Enum: []string{"MERGE_MESSAGE", "PR_TITLE"}},
		"name":                         {Type: "string"},
		"private":                      {Type: "boolean"},
		"pull_request_creation_policy": {Type: "string", Enum: []string{"all", "collaborators_only"}},
		"security_and_analysis": {Type: "object", Fields: map[string]Field{
			"advanced_security": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
			"code_security": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
			"secret_scanning": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
			"secret_scanning_ai_detection": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
			"secret_scanning_delegated_alert_dismissal": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
			"secret_scanning_delegated_bypass": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
			"secret_scanning_delegated_bypass_options": {Type: "object", Fields: map[string]Field{
				"reviewers": {Type: "array"},
			}},
			"secret_scanning_non_provider_patterns": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
			"secret_scanning_push_protection": {Type: "object", Fields: map[string]Field{
				"status": {Type: "string"},
			}},
		}},
		"squash_merge_commit_message":    {Type: "string", Enum: []string{"BLANK", "COMMIT_MESSAGES", "PR_BODY"}},
		"squash_merge_commit_title":      {Type: "string", Enum: []string{"COMMIT_OR_PR_TITLE", "PR_TITLE"}},
		"use_squash_pr_title_as_default": {Type: "boolean"},
		"visibility":                     {Type: "string", Enum: []string{"private", "public"}},
		"web_commit_signoff_required":    {Type: "boolean"},
	},
	Nodes: map[string]Node{
		"actions": Node{
			Kind:    KindNamespace,
			Segment: "actions",
			Nodes: map[string]Node{
				"permissions": Node{
					Kind:    KindObject,
					Segment: "permissions",
					Method:  "PUT",
					// from PUT /repos/{owner}/{repo}/actions/permissions
					Fields: map[string]Field{
						"allowed_actions":      {Type: "string", Enum: []string{"all", "local_only", "selected"}},
						"enabled":              {Type: "boolean"},
						"sha_pinning_required": {Type: "boolean"},
					},
					Nodes: map[string]Node{
						"artifact-and-log-retention": Node{
							Kind:    KindObject,
							Segment: "artifact-and-log-retention",
							Method:  "PUT",
							// from PUT /repos/{owner}/{repo}/actions/permissions/artifact-and-log-retention
							Fields: map[string]Field{
								"days": {Type: "integer"},
							},
						},
						"fork-pr-contributor-approval": Node{
							Kind:    KindObject,
							Segment: "fork-pr-contributor-approval",
							Method:  "PUT",
							// from PUT /repos/{owner}/{repo}/actions/permissions/fork-pr-contributor-approval
							Fields: map[string]Field{
								"approval_policy": {Type: "string", Enum: []string{"all_external_contributors", "first_time_contributors", "first_time_contributors_new_to_github"}},
							},
						},
						"selected-actions": Node{
							Kind:        KindObject,
							Segment:     "selected-actions",
							Method:      "PUT",
							Conditional: true,
							// from PUT /repos/{owner}/{repo}/actions/permissions/selected-actions
							Fields: map[string]Field{
								"github_owned_allowed": {Type: "boolean"},
								"patterns_allowed":     {Type: "array"},
								"verified_allowed":     {Type: "boolean"},
							},
						},
						"workflow": Node{
							Kind:    KindObject,
							Segment: "workflow",
							Method:  "PUT",
							// from PUT /repos/{owner}/{repo}/actions/permissions/workflow
							Fields: map[string]Field{
								"can_approve_pull_request_reviews": {Type: "boolean"},
								"default_workflow_permissions":     {Type: "string", Enum: []string{"read", "write"}},
							},
						},
					},
				},
				"variables": Node{
					Kind:    KindCollection,
					Segment: "variables",
					Method:  "POST",
					// from POST /repos/{owner}/{repo}/actions/variables
					Fields: map[string]Field{
						"name":  {Type: "string"},
						"value": {Type: "string"},
					},
				},
			},
		},
		"environments": Node{
			Kind:    KindCollection,
			Segment: "environments",
			Method:  "PUT",
			// from PUT /repos/{owner}/{repo}/environments/{environment_name}
			Fields: map[string]Field{
				"deployment_branch_policy": {Type: "object", Fields: map[string]Field{
					"custom_branch_policies": {Type: "boolean"},
					"protected_branches":     {Type: "boolean"},
				}},
				"prevent_self_review": {Type: "boolean"},
				"reviewers":           {Type: "array"},
				"wait_timer":          {Type: "integer"},
			},
			Nodes: map[string]Node{
				"variables": Node{
					Kind:    KindCollection,
					Segment: "variables",
					Method:  "POST",
					// from POST /repos/{owner}/{repo}/environments/{environment_name}/variables
					Fields: map[string]Field{
						"name":  {Type: "string"},
						"value": {Type: "string"},
					},
				},
			},
		},
		"rulesets": Node{
			Kind:    KindCollection,
			Segment: "rulesets",
			Method:  "POST",
			// from POST /repos/{owner}/{repo}/rulesets
			Fields: map[string]Field{
				"bypass_actors": {Type: "array"},
				"conditions": {Type: "object", Fields: map[string]Field{
					"ref_name": {Type: "object", Fields: map[string]Field{
						"exclude": {Type: "array"},
						"include": {Type: "array"},
					}},
				}},
				"enforcement": {Type: "string", Enum: []string{"active", "disabled", "evaluate"}},
				"name":        {Type: "string"},
				"rules":       {Type: "array"},
				"target":      {Type: "string", Enum: []string{"branch", "push", "tag"}},
			},
		},
	},
}
